# Netlify configuration for Deadhang Timer PWA
[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (contains the built files)
  publish = "dist"
  
  # Node.js version
  environment = { NODE_VERSION = "20" }

[build.processing]
  # Skip processing of some file types (they're already optimized)
  skip_processing = false

[build.processing.css]
  # CSS minification and bundling
  bundle = true
  minify = true

[build.processing.js]
  # JavaScript minification and bundling  
  bundle = true
  minify = true

[build.processing.html]
  # HTML minification
  pretty_urls = true

[build.processing.images]
  # Image compression
  compress = true

# PWA and Service Worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/manifest+json; charset=utf-8"

# Audio files caching
[[headers]]
  for = "/audio/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Static assets caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML caching (short-lived for updates)
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Enable compression
[[headers]]
  for = "/*"
  [headers.values]
    # Enable gzip compression
    X-Content-Type-Options = "nosniff" 